### ISSUE TITLE
support disabling OSC1

### ISSUE THREAD

**Issue by jordens** [sinara-hw/EEM_FMC_Carrier#10]
The muxes have very limited isolation. It helps a lot to be able to turn of the oscillator.
The crosstalk from the always-on clocks (potentially MMCX and PE) might still be a killer and may require desoldering of jumpers.
Also make sure there is guaranteed to be some clock available when the bitstream loads (pulls on CLK_SEL seem to be that one 10k down and the weak internal ups on the gpio extender, and OSC1:OE).

**Comment by marmeladapk** [comment]
Done.
