### ISSUE TITLE
DDR3 CK is not connected to CC pins

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/EEM_FMC_Carrier#19]
UG586 p.102: `CK must be connected to a clock capable (CCIO) p-n pair in one of the control byte
groups`

**Comment by marmeladapk** [comment]
Which version of this guide are you using? In v4.2 it states: "CK must be connected to a p-n pair in one of the control byte groups. Any p-n pair in the group is acceptable, including SRCC, MRCC, and DQS pins." It's only an output from an FPGA, so it's weird. Plus current placement passes MIG check in Vivado.

**Comment by filipswit** [comment]
You are right! Unfortunately v1.3 is the first in google search.
