### ISSUE TITLE
I2C MUX voltage translation

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/EEM_FMC_Carrier#22]
I'm not sure if it can translate voltages from smaller Vcc to higher bus supply.

DS: `The pass-gate transistors of the TCA9548A are constructed such that the VCC voltage can be used to limit the
maximum voltage that is passed from one I
2C bus to another.
`

**Comment by marmeladapk** [comment]
I'm fairly certain, that it should work both ways, but just in case I'll add pads for PCA9306.

**Comment by marmeladapk** [comment]
@filipswit Could you check if these changes are correct?

**Comment by filipswit** [comment]
Looks fine.
