### ISSUE TITLE
EFC cannot work standalone in EEM variant

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/EEM_FMC_Carrier#43]
Due to lack of P3V3 MP.

Probably IC14 should be present in both variants with logic that disables it if P3V3_MP from EEM connector is present.

**Comment by gkasprow** [comment]
EEM in stand-alone mode can also work as a controller so let's populate it by default. Maybe add  a diode instead of R278

**Comment by marmeladapk** [comment]
Additionally after enabling servmod with no P3V3_MP I2C bus will be stuck low.

**Comment by gkasprow** [comment]
For some unknown reason somebody removed SERVMOD activated I2C switch. It was there in initial version of EEM-DIOT adapters. I2C bus is shared among the chassis so all EEPROMs are connected in parallel.
