### ISSUE TITLE
~0.5V at Pin 32 of ADCLK948BCPZ (IN_SEL)

### ISSUE THREAD

**Issue by occheung** [sinara-hw/EEM_FMC_Carrier#48]
Here's some hardware context of my card (that I can observe):
- Pin 32 of ADCLK948BCPZ is the IN_SEL pin
- IN_SEL and CLK_SEL1 are NOT connected (No R77 in between)
- There is R3 between IN_SEL and GND

Found ~470 mV at the IN_SEL pin.

**Comment by gkasprow** [comment]
it looks there is some pullup resistance inside
![obraz](https://github.com/sinara-hw/EEM_FMC_Carrier/assets/4325054/a13bf492-d6fe-4eba-b6c8-05c6a1f35cae)
replace R3 with 1k
