### ISSUE TITLE
larger FPGA

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/EEM_FMC_Carrier#51]
The 200T appears to be pin-compatible, and for Shuttler would allow sigma-delta modulation to increase effective bit depth, additional DDS tones, and perhaps a better RTIO interface with one dedicated channel per coefficient.

Currently we are approaching the limit of the 100T.

**Comment by dhslichter** [comment]
I would support this -- it certainly makes for a more general-purpose board, and would be good for Shuttler specifically as well. @gkasprow what's the price difference between 100T and 200T with your pricing breaks?

**Comment by marmeladapk** [comment]
We can also consider supporting [DIOT FMC Carrier](
https://ohwr.org/project/diot-pfc-ku/wikis/home). EFC was in fact based on
diot carrier in many ways.

wt., 12 wrz 2023, 23:37 użytkownik Daniel Slichter ***@***.***>
napisał:

**Comment by dhslichter** [comment]
> We can also consider supporting [DIOT FMC Carrier](
https://ohwr.org/project/diot-pfc-ku/wikis/home).

This is a comment for a different issue, and I agree with @sbourdeauducq that these are two different boards and we shouldn't try to merge them.

The question here is simply if we can make a run of EFC boards with the 200T populated instead of the 100T. I would be strongly in favor of this and we would prefer to buy boards with 200T than 100T.

**Comment by gkasprow** [comment]
I think we can providing that vccint power supply is sufficient. About pricing it's a question to @pkozakiewicz

**Comment by pkozakiewicz** [comment]
@gkasprow Can you please create a release so that I can pass it to the right person?

**Comment by gkasprow** [comment]
the new relese is still in progress.
Just replace XC7A100T-3FGG484E with XC7A200T-3FGG484

**Comment by pkozakiewicz** [comment]
There is no production documentation even when it comes to the old one.

**Comment by marmeladapk** [comment]
That's my bad. I'll make a release shortly.

**Comment by pkozakiewicz** [comment]
> Just replace XC7A100T-3FGG484E with XC7A200T-3FGG484

There's no such chip, did you mean 3FBG?

**Comment by dhslichter** [comment]
seems worth it to me, overall. Can @sbourdeauducq or @jordens comment on the extent to which the slightly higher worst-case clock tree skew might impact existing (or currently envisioned) gateware designs? 0.27 ns (100T) vs 0.4 ns (200T) in speed grade -3.

**Comment by jordens** [comment]
I don't think it matters but to give a reliable answer it would obviously need to be tested. 

Crucially though it doesn't seem worthwhile to persue given what's been said. I can fit more than 128 well designed NCO cores and copious amounts of DS modulators and interpolators on a single 100T already.
