### ISSUE TITLE
LVDS pins clock capable not routed or connected to non clock capable pins

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/EEM_FMC_Carrier#54]
Check and verify:

https://ohwr.org/project/diot-pfc-ku/issues/107

We use similar pin assignment.

**Comment by kaolpr** [comment]
I don't get that issue. To me it looks like someone took a specific application where clocking is delivered (for some reason) via LVDS1 / LVDS7 and requested physical rerouting on PCB.
