### ISSUE TITLE
schematic review

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/EEM_FMC_Carrier#9]
- swap HB17 with HB21, HB17 must be CC
![obraz](https://user-images.githubusercontent.com/4325054/132998668-06e64c4f-9205-46ba-b531-c196b8e3782c.png)

- shouldn't the CC pins be connected to MRCC instead of SRCC where possible?
- what about adding decoupling caps to FMC_VREFxx ?

**Comment by marmeladapk** [comment]
> swap HB17 with HB21, HB17 must be CC

Done

> shouldn't the CC pins be connected to MRCC instead of SRCC where possible?

Done, I connected primary CC to MRCC where possible.

> what about adding decoupling caps to FMC_VREFxx ?

FMC_VREFB caps were missing, added to FPGA_FMC sheet.

Thanks!
